### ISSUE TITLE
to use regexes the option --enable-unicode-properties must be provided

### ISSUE THREAD

**Issue by eko234** [kaushalmodi/hello_musl#6]
Hi, thanks for this, it was incredibly helpful to me, I found out I was getting some errors regarding regular expressions, turns out
for them to work one must pass the --enable-unicode-properties flag to the pcre config command, this is more a pcre thing anyway, but I think talking about it would be cool, anyhow if someone has the same issue I had this issue could be a good place to look.

Thanks once again!

**Comment by kaushalmodi** [comment]
Normal regex works without that switch. Are you trying to enable support of unicode characters?

**Comment by kaushalmodi** [comment]
Also, can you provide a minimal example that fails if pcre is not compiled with that switch?

Thanks.

**Comment by eko234** [comment]
Hi again, look, my error is exactly the one the OP mentions in: https://github.com/crystal-lang/crystal/issues/2662,
I'm using `import regex` and I'm using the following regexes to get the plain name of a file without path or extension
``` nim
const b1 = re"/(.*)\.[^.]+$"
const b2 = re"\.tales/(.*)"

proc ListTales(): seq[string] =
  for file in walkFiles("./tales/*"):
    result.add file.replace(b1, "$1").replace(b2, "$1")
```
This might not be the best way to achieve this but it works, it seems that also the package `markdown` that uses regular expressions extensively fails if we don't compile pcre with said flag, 

``` nim
  if title in ListTales():
    readFile("./tales/" & title & ".md")
      .markdown
```

at least the use of markdown library should fail, I really couldn't test the other part, setting the flag in the config file solved
it.

**Comment by eko234** [comment]
``` nim
when not defined(usePcreHeader):
  when hostOS == "windows":
    when defined(nimOldDlls):
      const pcreDll = "pcre.dll"
    elif defined(cpu64):
      const pcreDll = "pcre64.dll"
    else:
      const pcreDll = "pcre32.dll"
  elif hostOS == "macosx":
    const pcreDll = "libpcre(.3|.1|).dylib"
  else:
    const pcreDll = "libpcre.so(.3|.1|)"
  {.push dynlib: pcreDll.}
else:
  {.push header: "<pcre.h>".}

```

Upon closer inspection I think it might be due to the `markdown` package, this is found in the package that uses pcre.

**Comment by eko234** [comment]
This is a `markdown` package issue as far as I can tell, sorry to bother you, the config is extensible enough to work it around if you understand well your dependencies, thanks again for your work.
